### ISSUE TITLE
LangExplorer、EntityView定義を開くとエラーが発生する

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#425]
LangExplorer、EntityView定義を開くとエラーが発生する。

```
ERROR 60 171486   o.i.a.s.base.rpc.i18n.LangDataLogic - org.iplass.mtp.view.generic.element.section.SearchResultSection.getLocalizedBulkUpdateDisplayLabelList()
java.lang.NoSuchMethodException: org.iplass.mtp.view.generic.element.section.SearchResultSection.getLocalizedBulkUpdateDisplayLabelList()
	at java.lang.Class.getMethod(Class.java:1786)
	at org.iplass.adminconsole.server.base.rpc.i18n.LangDataLogic.createMultiLangItemInfo(LangDataLogic.java:105)
	at org.iplass.adminconsole.server.base.rpc.i18n.LangDataLogic.createMultiLangItemInfo(LangDataLogic.java:76)
	at org.iplass.adminconsole.server.base.rpc.i18n.LangDataLogic.createMultiLangItemInfo(LangDataLogic.java:167)
	at org.iplass.adminconsole.server.base.rpc.i18n.LangDataLogic.createMultiLangItemInfo(LangDataLogic.java:76)
	at org.iplass.adminconsole.server.base.rpc.i18n.LangDataLogic.createMultiLangInfo(LangDataLogic.java:66)
	at org.iplass.adminconsole.server.base.rpc.i18n.LangDataLogic.createMultiLangItemInfo(LangDataLogic.java:165)
	at org.iplass.adminconsole.server.base.rpc.i18n.LangDataLogic.createMultiLangItemInfo(LangDataLogic.java:76)
	at org.iplass.adminconsole.server.base.rpc.i18n.LangDataLogic.createMultiLangInfo(LangDataLogic.java:66)
```

**Comment by xkazama-yukio3** [comment]
_(English)_
Error occurs when EntityView definition is opened on LangExplorer.

```
ERROR 60 171486   o.i.a.s.base.rpc.i18n.LangDataLogic - org.iplass.mtp.view.generic.element.section.SearchResultSection.getLocalizedBulkUpdateDisplayLabelList()
java.lang.NoSuchMethodException: org.iplass.mtp.view.generic.element.section.SearchResultSection.getLocalizedBulkUpdateDisplayLabelList()
	at java.lang.Class.getMethod(Class.java:1786)
	at org.iplass.adminconsole.server.base.rpc.i18n.LangDataLogic.createMultiLangItemInfo(LangDataLogic.java:105)
	at org.iplass.adminconsole.server.base.rpc.i18n.LangDataLogic.createMultiLangItemInfo(LangDataLogic.java:76)
	at org.iplass.adminconsole.server.base.rpc.i18n.LangDataLogic.createMultiLangItemInfo(LangDataLogic.java:167)
	at org.iplass.adminconsole.server.base.rpc.i18n.LangDataLogic.createMultiLangItemInfo(LangDataLogic.java:76)
	at org.iplass.adminconsole.server.base.rpc.i18n.LangDataLogic.createMultiLangInfo(LangDataLogic.java:66)
	at org.iplass.adminconsole.server.base.rpc.i18n.LangDataLogic.createMultiLangItemInfo(LangDataLogic.java:165)
	at org.iplass.adminconsole.server.base.rpc.i18n.LangDataLogic.createMultiLangItemInfo(LangDataLogic.java:76)
	at org.iplass.adminconsole.server.base.rpc.i18n.LangDataLogic.createMultiLangInfo(LangDataLogic.java:66)
```

**Comment by xkazama-yukio3** [comment]
SearchResultSectionの「一括更新ボタン表示ラベル」の多言語側のgetter、setterが、デフォルトのメソッド名と異なるため。

```
/** 一括更新ボタン表示ラベル */
@MetaFieldInfo(
		displayName="一括更新ボタン表示ラベル",
		displayNameKey="generic_element_section_SearchResultSection_bulkUpdateDisplayLabelDisplaNameKey",
		description="一括更新ボタンに表示されるラベルを設定します。",
		descriptionKey="generic_element_section_SearchResultSection_bulkUpdateDisplayLabelDescriptionKey",
		inputType=InputType.MULTI_LANG,
		multiLangField = "localizedBulkUpdateDisplayLabel",
		displayOrder=300
)
@MultiLang()
private String bulkUpdateDisplayLabel;

/** 多言語設定情報 */
@MetaFieldInfo(
		displayName="多言語設定",
		displayNameKey="generic_element_section_SearchResultSection_localizedBulkUpdateDisplayLabelDisplaNameKey",
		inputType=InputType.MULTI_LANG_LIST,
		displayOrder=310
)
private List<LocalizedStringDefinition> localizedBulkUpdateDisplayLabel;

```

デフォルトでは、`get` + multiLangField + `List` というメソッド名で検索に行くが、
`localizedBulkUpdateDisplayLabel` は、 `getLocalizedBulkUpdateDisplayLabel` と定義していて Suffixに `List` がないため。

**Comment by xkazama-yukio3** [comment]
既存定義を考慮して、
MultiLangアノテーションで、 `multiLangGetter` `multiLangSetter` で対応する。
