### ISSUE TITLE
storage_space_migrateバッチ&clean_storage_spaceバッチ：mtp、userから削除する場合エラー

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#782]
storage_space_migrateバッチ&clean_storage_spaceバッチ、mtp、userから削除する場合エラー。
原因はmtpストレージスペースは外部INDEXテーブル作ってないので。

stacktrace抜粋
Caused by: java.sql.SQLSyntaxErrorException: Table 'mtdb.obj_index_date__mtp' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)

storage_space_migrateバッチとclean_storage_spaceバッチで外部INDEXテーブルの利用有無をチェックするようにする。

**Comment by xsuzukiyosuke** [comment]
_(English)_
storage_space_migrate batch and clean_storage_space batch, it occur error when it clean from mtp and user.
Because mtp storage space don't make external index table.

stacktrace excerpt
Caused by: java.sql.SQLSyntaxErrorException: Table 'mtdb.obj_index_date__mtp' doesn't exist
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)

Check whether to use of external index table at storage_space_migrate batch and clean_storage_space batch.
